# Managed File... Don't Edit
export PATH=$HOME/bin:$PATH
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

export PATH="$HOME/.cargo/bin:$PATH"